# Generated by Django 5.0.2 on 2026-02-24 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='task',
            name='shared_id',
            field=models.CharField(blank=True, help_text='Short ID for agents to reference this task', max_length=50, null=True, unique=True),
        ),
    ]
